import * as React from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import JobPostForm from '@/components/JobPostForm'
import { useRouter } from 'next/router'
import JobData from '@/interfaces/Job'
import { Backdrop, CircularProgress } from '@mui/material'

type serverProps = {
  params: {
    id: number
  }
}

export async function getServerSideProps({ params }: serverProps) {
  return {
      props: { id: params.id }
  }
}

export default function JobEditPage() {
  const router = useRouter()
  const { id } = router.query

  const [uid, setUid] = React.useState<string | undefined>(undefined)
  const [pageLoading, setPageLoading] = React.useState<boolean>(true)
  const handleComplete = () => { setPageLoading(false) }

  React.useEffect(() => {
    setUid(id as string)
    handleComplete()
  }, [id])

  const save = (data: JobData) => {
    fetch('/api/job-posts/save', {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    }).then(res => {
      console.log(res.json())
    })
    router.push('/')
  }
  return (
    <>
      <Head>
        <title>Job Post App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Backdrop
          sx={{ color: '#fff', zIndex: (theme) => theme.zIndex.drawer + 1 }}
          open={pageLoading}
        >
          <CircularProgress color="success" />
        </Backdrop>
        {
          uid && <JobPostForm uid={uid} onSave={save}/>
        }
      </main>
    </>
  )
}
