import * as React from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import JobPostForm from '@/components/JobPostForm'
import { useRouter } from 'next/router'
import JobData from '@/interfaces/Job'
import { Backdrop, CircularProgress } from '@mui/material'
import UserObj from '@/interfaces/User'

type serverProps = {
  params: {
    id: number
  }
}

export async function getServerSideProps({ params }: serverProps) {
  return {
    props: { id: params.id }
  }
}

export default function JobEditPage() {
  const router = useRouter()
  const { id } = router.query

  const [jobId, setJobId] = React.useState<string | undefined>(undefined)
  const [pageLoading, setPageLoading] = React.useState<boolean>(true)
  const [user, setUser] = React.useState<UserObj | null>(null)
  const handleComplete = () => { setPageLoading(false) }
  const checkLogin = () => {
    fetch('/api/auth/check').then(async (res) => {
      const data = await res.json()
      setUser(data)
    })
  }

  React.useEffect(() => {
    setJobId(id as string)
    handleComplete()

    checkLogin()
    if (user?.role == 'applicant') {
      router.push('/')
    }
  }, [id, user, router])

  const save = (data: JobData) => {
    fetch('/api/job-posts/save', {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    }).then(res => {
      console.log(res.json())
    })
    router.push('/')
  }
  return (
    <>
      <Head>
        <title>Edit Job Post</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Backdrop
          sx={{ color: '#fff', zIndex: (theme) => theme.zIndex.drawer + 1 }}
          open={pageLoading}
        >
          <CircularProgress color="success" />
        </Backdrop>
        {
          jobId && <JobPostForm jobId={jobId} onSave={save}/>
        }
      </main>
    </>
  )
}
