import * as React from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import JobPostForm from '@/components/JobPostForm'
import JobData from '@/interfaces/Job'
import { useRouter } from 'next/router'
import UserObj from '@/interfaces/User'
import { error } from 'console'

export default function JobAddPage() {
  const router = useRouter()
  const [user, setUser] = React.useState<UserObj | null>(null)
  const save = (data: JobData) => {
    fetch('/api/job-posts/save', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    }).then(res => {
      console.log(res.json())
    })

    router.push('/')
  }
  const checkLogin = () => {
    fetch('/api/auth/check').then(async (res) => {
      const data = await res.json()
      setUser(data)
    }).catch((error) => {
      console.log(error)
      setUser(null)
    })
  }

  React.useEffect(() => {
    checkLogin()
    console.log(user?.role == 'applicant')
    if (!user || user?.role == 'applicant') {
      router.push('/')
    }
  }, [user, router])

  return (
    <>
      <Head>
        <title>Add Job Post</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <JobPostForm onSave={save}/>
      </main>
    </>
  )
}
