import * as React from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import JobPostForm from '@/components/JobPostForm'
import JobData from '@/interfaces/Job'
import { useRouter } from 'next/router'

export default function JobAddPage() {
  const router = useRouter()
  const save = (data: JobData) => {
    fetch('/api/job-posts/save', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    }).then(res => {
      console.log(res.json())
    })

    router.push('/')
  }

  return (
    <>
      <Head>
        <title>Job Post App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <JobPostForm onSave={save}/>
      </main>
    </>
  )
}
