import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import JobPost from '@/components/JobPost'
import Job from '@/interfaces/Job'
import jobData from '@/pages/api/job-listing.json'

const inter = Inter({ subsets: ['latin'] })
let jobs: Job[] = jobData

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.grid}>
        {
          jobs.map((job, idx) =>
            <a
              key={idx}
              href="#"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <JobPost
                title={job.title}
                company={job.company}
                description={job.description}
              />
            </a>
          )
        }
        </div>
      </main>
    </>
  )
}
