import * as React from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Typography from '@mui/material/Typography'
import { Box } from '@mui/material'

export default function JobConfirmPage() {
  const router = useRouter()
  const query = router.query
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Box sx={{ width: '100%', maxWidth: 500 }}>
          <Typography variant="h5">
            Thank you for applying <Box fontWeight='fontWeightMedium' display='inline'>{query.name}</Box>, we will send you more details at <Box fontWeight='fontWeightMedium' display='inline'>{query.email_address}</Box>.
            Just to recap this is the reason that you gave on why we should hire you: <Box fontWeight='fontWeightMedium' display='inline'>{query.reason}</Box>
          </Typography>
        </Box>
      </main>
    </>
  )
}